name: Tag Release

on:
  push:
    branches:
      - main
    paths:
      - 'custom_components/coral_mylo/manifest.json'

jobs:
  tag-release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - id: version
        run: |
          VERSION=$(jq -r '.version' custom_components/coral_mylo/manifest.json)
          echo "version=$VERSION" >> "$GITHUB_OUTPUT"
      - id: check
        run: |
          git fetch --tags
          if git rev-parse "${{ steps.version.outputs.version }}" >/dev/null 2>&1; then
            echo "exists=true" >> "$GITHUB_OUTPUT"
          else
            echo "exists=false" >> "$GITHUB_OUTPUT"
          fi
      - name: Create release
        if: steps.check.outputs.exists == 'false'
        uses: ncipollo/release-action@v1
        with:
          tag: ${{ steps.version.outputs.version }}
          commit: ${{ github.sha }}
          generateReleaseNotes: true
